import type { ReactNode } from "react";
import { Activity, ArrowRight, Check, CircleAlert, Database, Eye, FlaskConical, Image as ImageIcon, Layers3, Microscope, ScanSearch, Server, ShieldAlert, SlidersHorizontal, UploadCloud } from "lucide-react";
import { SlideLayout } from "./SlideLayout";
import p1 from "@/assets/samples/p1.jpg";
import p2 from "@/assets/samples/p2.jpg";
import p3 from "@/assets/samples/p3.jpg";
import u1 from "@/assets/samples/u1.jpg";
import u2 from "@/assets/samples/u2.jpg";
import u3 from "@/assets/samples/u3.jpg";

const images = [p1, p2, p3, u1, u2, u3];
const slides: { title: string; section: string; dark?: boolean; content: ReactNode }[] = [
  { title: "SmearScan", section: "THE PROJECT", dark: true, content: <div className="slide-hero">
    <div className="slide-hero-copy"><div className="slide-kicker">MALARIA OUTCOME PREDICTION</div><h1 className="slide-title-lg">SmearScan<span className="slide-accent-dot">.</span></h1><p className="slide-subtitle">Detecting signs of malaria parasites in blood smear images with deep learning.</p><div className="slide-hero-footer"><span>EfficientNetV2S</span><span>Blood smear image classification</span><span>Binary prediction</span></div></div>
    <div className="slide-hero-image"><img src={p1} alt="Illustrative parasitized blood smear sample" /><span className="slide-image-label">ILLUSTRATIVE SAMPLE IMAGE</span></div>
  </div> },
  { title: "The problem", section: "01 / CONTEXT", content: <div className="slide-main"><div className="slide-kicker">WHY THIS MATTERS</div><h2 className="slide-title">Malaria diagnosis begins with a closer look.</h2><div className="slide-split"><div><p className="slide-body-lg">Microscopy remains important for identifying parasites in blood samples, but reviewing many images takes time and skilled attention.</p><p className="slide-body slide-muted">A computer-assisted first pass could help flag images for review — not replace a trained professional.</p></div><div className="slide-photo-block"><img src={p2} alt="Illustrative blood smear microscopy image"/><span>ILLUSTRATIVE MICROSCOPY SAMPLE</span></div></div></div> },
  { title: "The idea", section: "02 / SOLUTION", dark: true, content: <div className="slide-main"><div className="slide-kicker">OUR APPROACH</div><h2 className="slide-title">From image to an actionable flag.</h2><div className="slide-flow"><div><UploadCloud/><strong>01</strong><h3>Upload</h3><p>JPG or PNG blood smear images, individually or in a batch.</p></div><ArrowRight className="slide-flow-arrow"/><div><ScanSearch/><strong>02</strong><h3>Analyze</h3><p>An image classifier estimates the likelihood of parasitization.</p></div><ArrowRight className="slide-flow-arrow"/><div><Eye/><strong>03</strong><h3>Review</h3><p>Each image receives a positive or negative prediction.</p></div></div></div> },
  { title: "Dataset & preparation", section: "03 / DATA", content: <div className="slide-main"><div className="slide-kicker">INPUTS</div><h2 className="slide-title">Two classes. One consistent image pipeline.</h2><div className="slide-compare"><div className="slide-compare-image"><img src={p3} alt="Illustrative parasitized class sample"/><span>PARASITIZED</span></div><div className="slide-compare-image"><img src={u1} alt="Illustrative uninfected class sample"/><span>NON-PARASITIZED</span></div><div className="slide-compare-copy"><h3>Preprocessing</h3><p>Images are resized to 150 × 150 pixels, converted to RGB, and pixel values are scaled to 0–1.</p><p className="slide-caption">Training used augmentation to introduce variation. Replace illustrative images with verified dataset examples before claiming visual ground truth.</p></div></div></div> },
  { title: "The model", section: "04 / MODEL", content: <div className="slide-main"><div className="slide-kicker">ARCHITECTURE</div><h2 className="slide-title">EfficientNetV2S powers the classifier.</h2><div className="slide-model"><div className="slide-model-step"><ImageIcon/><span>150 × 150 RGB</span></div><ArrowRight/><div className="slide-model-step"><Layers3/><span>EfficientNetV2S</span></div><ArrowRight/><div className="slide-model-step"><Activity/><span>Global pooling + dense</span></div><ArrowRight/><div className="slide-model-step"><SlidersHorizontal/><span>Sigmoid score</span></div></div><div className="slide-info-row"><div><strong>Training objective</strong><span>Binary cross-entropy</span></div><div><strong>Optimizer</strong><span>Adam with staged learning rates</span></div><div><strong>Decision cutoff</strong><span>0.70 for a positive flag</span></div></div></div> },
  { title: "Decision rule", section: "05 / INFERENCE", dark: true, content: <div className="slide-main"><div className="slide-kicker">HOW TO READ THE OUTPUT</div><h2 className="slide-title">One score. A clear decision rule.</h2><div className="slide-threshold"><div className="slide-threshold-number">0.70</div><div><p className="slide-body-lg">If the model score is <strong>at least 0.70</strong>, the image is flagged <strong>Positive</strong>.</p><p className="slide-body">Below 0.70, it is labeled Negative.</p><p className="slide-caption">The score estimates the parasitized class; it is not a species label or a clinical diagnosis.</p></div></div></div> },
  { title: "The web app", section: "06 / EXPERIENCE", content: <div className="slide-main"><div className="slide-kicker">WHAT WE BUILT</div><h2 className="slide-title">A practical review interface.</h2><div className="slide-feature-grid"><div><Database/><h3>Patient context</h3><p>Patient ID, age, and sex.</p></div><div><UploadCloud/><h3>Batch upload</h3><p>Drag and drop or browse up to 10 JPG/PNG images.</p></div><div><Microscope/><h3>Image preview</h3><p>Preview grid with per-image status badges.</p></div><div><Check/><h3>Results</h3><p>Individual positive/negative labels and a batch summary.</p></div></div></div> },
  { title: "System connection", section: "07 / IMPLEMENTATION", content: <div className="slide-main"><div className="slide-kicker">FRONTEND + BACKEND</div><h2 className="slide-title">The browser and model work together.</h2><div className="slide-system"><div><UploadCloud/><h3>Web interface</h3><p>Collects patient details and image files.</p></div><ArrowRight/><div><Server/><h3>Python API</h3><p>Receives the batch and preprocesses each image.</p></div><ArrowRight/><div><FlaskConical/><h3>Trained model</h3><p>Returns scores and labels for display.</p></div></div><p className="slide-caption slide-system-note">A live server needs the trained .h5 file. Without a connected server, the app explicitly marks predictions as simulated demo results.</p></div> },
  { title: "Results", section: "08 / EVALUATION", dark: true, content: <div className="slide-main"><div className="slide-kicker">EVIDENCE</div><h2 className="slide-title">What did the model achieve?</h2><div className="slide-results"><div><span>TEST ACCURACY</span><strong>[ADD VERIFIED VALUE]</strong></div><div><span>SENSITIVITY</span><strong>[ADD VERIFIED VALUE]</strong></div><div><span>SPECIFICITY</span><strong>[ADD VERIFIED VALUE]</strong></div></div><p className="slide-body slide-muted">Present the test-set confusion matrix and class counts alongside these measures. Do not use training accuracy as test performance.</p><p className="slide-caption">Re-evaluate with the same 150 × 150 preprocessing for both classes before filling these values.</p></div> },
  { title: "Live demonstration", section: "09 / DEMO", content: <div className="slide-main"><div className="slide-kicker">SHOW THE WORKFLOW</div><h2 className="slide-title">From smear image to prediction.</h2><div className="slide-demo"><div className="slide-demo-grid">{images.map((src, i) => <img key={i} src={src} alt={`Illustrative sample ${i + 1}`} />)}</div><ol><li><strong>01</strong> Enter a patient ID.</li><li><strong>02</strong> Add images or try the six samples.</li><li><strong>03</strong> Select “Analyze smear.”</li><li><strong>04</strong> Review labels for each image.</li></ol></div><p className="slide-caption">Samples are illustrative, AI-generated images. For a live model demonstration, confirm the model server is connected first.</p></div> },
  { title: "Limitations", section: "10 / RESPONSIBLE USE", content: <div className="slide-main"><div className="slide-kicker">WHAT IT DOES NOT DO</div><h2 className="slide-title">A research tool, not a diagnosis.</h2><div className="slide-limits"><div><CircleAlert/><p>Binary detection only: the model does not identify parasite species or measure parasite density.</p></div><div><ShieldAlert/><p>External validation and clinical review are needed before real-world use.</p></div><div><Eye/><p>Demo results are simulated when no model server is connected.</p></div></div></div> },
  { title: "Next steps", section: "11 / ROADMAP", dark: true, content: <div className="slide-main"><div className="slide-kicker">WHERE WE GO NEXT</div><h2 className="slide-title">Make it more explainable. More robust. More useful.</h2><div className="slide-next"><div><span>01</span><h3>Validate</h3><p>Measure performance on a held-out test set and independent smear data.</p></div><div><span>02</span><h3>Explain</h3><p>Visualize what image regions influence the prediction.</p></div><div><span>03</span><h3>Extend</h3><p>Explore species classification and parasite density estimation with suitable labels.</p></div></div></div> },
  { title: "Thank you", section: "QUESTIONS", dark: true, content: <div className="slide-outro"><div className="slide-kicker">SMEARSCAN / MALARIA OUTCOME PREDICTION</div><h2 className="slide-title-lg">Thank you<span className="slide-accent-dot">.</span></h2><p className="slide-subtitle">Questions?</p><div className="slide-outro-mark"><Microscope/></div></div> },
];
export const deck = slides.map((slide, index) => ({ ...slide, element: <SlideLayout dark={slide.dark ?? false} section={slide.section} number={index + 1}>{slide.content}</SlideLayout> }));
